on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::tidyverse
            any::raster
            any::terra
            any::caret
            any::randomForest
            any::twosamples
            any::mapview
            any::sf
            any::CAST
            any::tmap
            any::rprojroot           
            any::ggplot2
            any::patchwork
            any::kableExtra
            any::"sp"
            any::"dplyr"
            any::"lwgeom"
            any::"readxl"
            any::"highfrequency"
            any::"tidyverse"
            any::"tibble"
            any::"xts"
            any::"data.table"
            any::stars
            any::gstat
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}